controller:
  image:
    repository: quay.io/argoproj/argo-rollouts
    tag:             # defaults is the chart appVersion.
    pullPolicy: IfNotPresent

  resources:
  #  limits:
  #    cpu: 100m
  #    memory: 128Mi
  #  requests:
  #    cpu: 50m
  #    memory: 64Mi

  extraArgs:
  # - --aws-verify-target-group

notifications:
  # -- Includes the notifications ConfigMap with predefined notification templates
  enabled: false
  # -- Creates the notification Secret. Disable this if you create the secret in another way (e.g. SealedSecret)
  createSecret: true

dashboard:
  # -- Enables the rollout dashboard
  enabled: false

  image:
    repository: quay.io/argoproj/kubectl-argo-rollouts
    tag:        # defaults is the chart appVersion.
    pullPolicy: IfNotPresent

  resources:
  #  limits:
  #    cpu: 100m
  #    memory: 128Mi
  #  requests:
  #    cpu: 50m
  #    memory: 64Mi

  ingress:
    # -- Enable creation of Ingress object
    enabled: false

    host: rollouts.example.com
    annotations: {}
    className: ""

    tls:
      enabled: false
      secretName:
