{{- if and .Values.server.enabled .Values.server.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
{{- if .Values.server.ingress.annotations  }}
  annotations:
  {{- range $key, $value := .Values.server.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
spec:
{{- if .Values.server.ingress.ingressClassName }}
  ingressClassName: {{ .Values.server.ingress.ingressClassName }}
{{- end }}
  rules:
    - host: {{ .Values.server.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: argocd-server
                port:
                  number: {{ ternary "80" "443" .Values.server.insecure }}
            path: /
            pathType: Prefix
{{- if .Values.server.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.server.ingress.host }}
{{- with .Values.server.ingress.tls.secretName }}
    secretName: {{ . }}
{{- end }}
{{- end }}
{{- end }}