apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventsource-controller
spec:
  replicas: {{ .Values.eventsourceController.replicas }}
  selector:
    matchLabels:
      app: eventsource-controller
  template:
    metadata:
      labels:
        app: eventsource-controller
    spec:
      containers:
      - args:
        - eventsource-controller
        {{- with .Values.eventsourceController.extraArgs }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
        {{- with .Values.eventsourceController.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        env:
        - name: EVENTSOURCE_IMAGE
          value: {{ default .Values.global.image.repository .Values.eventsourceController.eventsourceImage.repository }}:{{ default .Values.global.image.tag .Values.eventsourceController.eventsourceImage.tag }}
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: {{ default .Values.global.image.repository .Values.eventsourceController.image.repository }}:{{ default .Values.global.image.tag .Values.eventsourceController.image.tag }}
        imagePullPolicy: {{ default .Values.global.image.pullPolicy .Values.eventsourceController.image.pullPolicy }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 3
          periodSeconds: 3
        name: eventsource-controller
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 3
          periodSeconds: 3
      securityContext:
        runAsNonRoot: true
        runAsUser: 9731
      serviceAccountName: argo-events-sa