apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventbus-controller
spec:
  replicas: {{ .Values.eventbusController.replicas }}
  selector:
    matchLabels:
      app: eventbus-controller
  template:
    metadata:
      labels:
        app: eventbus-controller
    spec:
      containers:
      - args:
        - eventbus-controller
        {{- with .Values.eventsourceController.extraArgs }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
        {{- with .Values.eventsourceController.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NATS_STREAMING_IMAGE
          value: {{ .Values.eventbusController.natsStreamingImage.repository }}:{{ .Values.eventbusController.natsStreamingImage.tag }}
        - name: NATS_METRICS_EXPORTER_IMAGE
          value: {{ .Values.eventbusController.natsMetricsExporterImage.repository }}:{{ .Values.eventbusController.natsMetricsExporterImage.tag }}
        image: {{ default .Values.global.image.repository .Values.eventbusController.image.repository }}:{{ default .Values.global.image.tag .Values.eventbusController.image.tag }}
        imagePullPolicy: {{ default .Values.global.image.pullPolicy .Values.eventbusController.image.pullPolicy }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 3
          periodSeconds: 3
        name: eventbus-controller
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 3
          periodSeconds: 3
      securityContext:
        runAsNonRoot: true
        runAsUser: 9731
      serviceAccountName: argo-events-sa