apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-controller
spec:
  replicas: {{ .Values.sensorController.replicas }}
  selector:
    matchLabels:
      app: sensor-controller
  template:
    metadata:
      labels:
        app: sensor-controller
    spec:
      containers:
      - args:
        - sensor-controller
        {{- with .Values.sensorController.extraArgs }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
        {{- with .Values.sensorController.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        env:
        - name: SENSOR_IMAGE
          value: {{ default .Values.global.image.repository .Values.sensorController.sensorImage.repository }}:{{ default .Values.global.image.tag .Values.sensorController.sensorImage.tag }}
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: {{ default .Values.global.image.repository .Values.sensorController.image.repository }}:{{ default .Values.global.image.tag .Values.sensorController.image.tag }}
        imagePullPolicy: {{ default .Values.global.image.pullPolicy .Values.sensorController.image.pullPolicy }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 3
          periodSeconds: 3
        name: sensor-controller
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 3
          periodSeconds: 3
      securityContext:
        runAsNonRoot: true
        runAsUser: 9731
      serviceAccountName: argo-events-sa