{{- if .Values.disasterRecovery.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-dr-s3
  annotations:
    {{- if .Values.disasterRecovery.eks }}
    eks.amazonaws.com/role-arn: {{ .Values.disasterRecovery.eks.roleARN | quote }}
    {{- end -}}
    {{- if .Values.disasterRecovery.gke }}
    iam.gke.io/gcp-service-account: {{ .Values.disasterRecovery.gke.gcpServiceAccount | quote }}
    {{- end -}}
{{- end }}
{{- if .Values.disasterRecovery.enabled }}
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-dr
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - get
  - list
  - create
  - update
  - patch
  - delete
- apiGroups:
  - argoproj.io
  resources:
  - applications
  - appprojects
  - applicationsets
  verbs:
  - get
  - list
  - create
  - update
  - patch
  - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-dr-s3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-dr
subjects:
- kind: ServiceAccount
  name: argocd-dr-s3
  namespace: {{ .Release.Namespace }}
{{- end }}
