{{- if .Values.disasterRecovery.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-dr
  annotations:
    {{- if .Values.disasterRecovery.aws }}
    eks.amazonaws.com/role-arn: {{ .Values.disasterRecovery.aws.roleARN | quote }}
    {{- end }}
    {{- if .Values.disasterRecovery.gcp }}
    iam.gke.io/gcp-service-account: {{ .Values.disasterRecovery.gcp.serviceAccount | quote }}
    {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-dr
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - get
  - list
  - create
  - update
  - patch
  - delete
- apiGroups:
  - argoproj.io
  resources:
  - applications
  - applicationsets
  verbs:
  - get
  - list
  - create
  - update
  - patch
  - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-dr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-dr
subjects:
- kind: ServiceAccount
  name: argocd-dr
{{- end }}
