{{- if .Values.notifications.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-rollouts-notification-configmap
  namespace: {{ .Release.Namespace }}
data:
{{- $currentScope := . }}
{{- range $path, $_ :=  .Files.Glob  "notifications/*" }}
    {{- with $currentScope}}
{{- .Files.Get $path | nindent 2 }}
    {{- end }}
{{ end }}
{{ end }}