{{- if .Values.notifications.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-rollouts-notification-configmap
data:
{{- $currentScope := . }}
{{- range $path, $_ :=  .Files.Glob  "notifications/*" }}
    {{- with $currentScope}}
  trigger.on-{{ base $path }}: |
    - send: [{{ base $path }}]
  template.{{ base $path }}: |
{{- .Files.Get $path | nindent 4 }}
    {{- end }}
{{ end }}
{{ end }}