image:
  # -- Default image repository
  repository: argoprojlabs/argocd-image-updater
  # -- Default image pull policy
  pullPolicy: Always
  # -- Default image tag
  tag: v0.11.3


# -- Extra arguments for argocd-image-updater not defined in config.argocd
extraArgs: []
  # - --disable-kubernetes
  # - --dry-run
  # - --health-port 8080
  # - --interval 2m
  # - --kubeconfig ~/.kube/config
  # - --match-application-name staging-*
  # - --max-concurrency 5
  # - --once
  # - --registries-conf-path /app/config/registries.conf

config:
  # -- ArgoCD Image Updater registries list configuration. More information [here](https://argocd-image-updater.readthedocs.io/en/stable/configuration/registries/)
  registries: []
    # - name: Docker Hub
    #   api_url: https://registry-1.docker.io
    #   ping: yes
    #   credentials: secret:foo/bar#creds
    #   defaultns: library
    # - name: Google Container Registry
    #   api_url: https://gcr.io
    #   prefix: gcr.io
    #   ping: no
    #   credentials: pullsecret:foo/bar
    # - name: RedHat Quay
    #   api_url: https://quay.io
    #   ping: no
    #   prefix: quay.io
    #   credentials: env:REGISTRY_SECRET
