apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-rollouts
  labels:
    app.kubernetes.io/component: rollouts-controller
    app.kubernetes.io/name: argo-rollouts
    app.kubernetes.io/part-of: argo-rollouts
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argo-rollouts
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argo-rollouts
    spec:
      serviceAccountName: argo-rollouts
      containers:
      - name: argo-rollouts
        image: {{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ default .Values.controller.image.pullPolicy }}
        {{- with .Values.controller.extraArgs }}
        args:
        {{- . | toYaml | nindent 8 }}
        {{- end }}
        {{- with .Values.controller.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        ports:
          - containerPort: 8090
            name: metrics
        livenessProbe:
          httpGet:
            path: /metrics
            port: 8090
          initialDelaySeconds: 30
          periodSeconds: 20
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /metrics
            port: 8090
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 4
      securityContext:
        runAsNonRoot: true
  strategy:
    type: Recreate
