apiVersion: v2
appVersion: 2.1.1
description: A Helm chart for ArgoCD, a declarative, GitOps continuous delivery tool for Kubernetes.
name: argo-cd
version: 0.0.2
home: https://github.com/argoproj/argo-helm
icon: https://argoproj.github.io/argo-cd/assets/logo.png
keywords:
  - argoproj
  - argocd
  - gitops
maintainers:
  - name: terrytangyuan
  - name: jessesuen
  - name: wanghong230
dependencies:
  - name: redis-ha
    version: 4.12.17
    repository: https://dandydeveloper.github.io/charts/
    condition: redis-ha.enabled
annotations:
  artifacthub.io/changes: |
    - "[Changed]: Make AWS ALB GRPC backend protocol version configurable"
