apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
{{- with .Values.config.params }}
data:
{{- toYaml . | nindent 2}}
{{- end }}