apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-gpg-keys-cm
  labels:
    app.kubernetes.io/name: argocd-gpg-keys-cm
    app.kubernetes.io/part-of: argocd
{{- with .Values.config.gpgKeys }}
data:
{{- toYaml . | nindent 2}}
{{- end }}