apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-tls-certs-cm
  labels:
    app.kubernetes.io/name: argocd-tls-certs-cm
    app.kubernetes.io/part-of: argocd
{{- with .Values.config.tlsCerts }}
data:
{{- toYaml . | nindent 4}}
{{- end }}
