apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-tls-certs-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-tls-certs-cm
  namespace: {{ .Release.Namespace }}
{{- with .Values.config.tlsCerts }}
data:
{{- toYaml . | nindent 4}}
{{- end }}
