apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
{{- with .Values.config.argocd }}
data:
{{- toYaml . | nindent 2}}
{{- end }}