{{- range $repo_key, $repo_value := .Values.config.repositories }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: argocd-repo-{{ $repo_key }}
  namespace: {{ .Release.Namespace }}
data:
  {{- range $key, $value := $repo_value }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
