{{- if .Values.notificationsController.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
type: Opaque
{{- end }}
