apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: server
  name: argocd-server-extensions
rules:
- apiGroups:
  - argoproj.io
  resources:
  - argocdextensions
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - delete
  - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: server
  name: argocd-server-extensions
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-server-extensions
subjects:
- kind: ServiceAccount
  name: argocd-server
