apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-image-updater-config
    app.kubernetes.io/part-of: argocd-image-updater
  name: argocd-image-updater-config
data:
  registries.conf: |
    {{- with .Values.config.registries }}
      registries:
        {{- toYaml . | nindent 6 }}
    {{- end }}
