name: Image Publish

on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  build-linux-amd64:
    name: Build & push linux/amd64
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        platform: [ linux/amd64 ]
        target: [ argocd ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_PASSWORD }}

      - name: Docker Push
        env:
          DOCKERIO_ORG: "quay.io"
        run: |
          SOURCE_REPO=argoproj
          TARGET_REPO=akuity
          docker pull ${DOCKERIO_ORG}/${SOURCE_REPO}/argocd:v2.1.1
          docker tag ${DOCKERIO_ORG}/${SOURCE_REPO}/argocd:v2.1.1 ${DOCKERIO_ORG}/${TARGET_REPO}/argocd:v0.0.1
          docker push ${DOCKERIO_ORG}/${TARGET_REPO}/argocd:v0.0.1
